services:
  postgres:
    container_name: ${PROJECT_NAME}-postgres
    image: postgres:16.3-alpine
    restart: unless-stopped
    environment:
      PGPASSWORD: '${DB_PASSWORD:-passw0rd}'
      POSTGRES_HOST: '${DB_HOST}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-passw0rd}'
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data:rw
  php-fpm:
    container_name: ${PROJECT_NAME}-php-fpm
    build:
      context: ./docker/php-fpm
      args:
        - PUID=${PUID}
        - PGID=${PGID}
    depends_on:
      - postgres
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./app/:/var/www/app/
    ports:
      - "9000:9000"
  apache:
    container_name: ${PROJECT_NAME}-apache
    build:
      context: ./docker/apache
    volumes:
      - ./app:/usr/local/apache2/htdocs/app:rw
      - ./docker/apache/conf:/usr/local/apache2/conf
      - ./docker/logs/apache:/var/www/logs:rw
    depends_on:
      - php-fpm
    ports:
      - "80:80"
      - "443:443"
    environment:
      - APACHE_DOCUMENT_ROOT=/usr/local/apache2/htdocs/app/public
      - APACHE_LOG_DIR=/var/www/logs
    extra_hosts:
      - host.docker.internal:${HOST_IP:-172.17.0.1}