#######################################
# Vhost for api
#######################################

<VirtualHost *:80>
  ServerName localhost
  ServerAlias www.localhost

  Redirect permanent / https://localhost/
</VirtualHost>

<VirtualHost *:443>
  ServerName localhost
  ServerAlias www.localhost

  SSLEngine on
  SSLCertificateFile /usr/local/apache2/conf/ssl/apache.crt
  SSLCertificateKeyFile /usr/local/apache2/conf/ssl/apache.key

  DocumentRoot /var/www/localhost/htdocs/app/public

  <Directory /var/www/localhost/htdocs/app/>
    Require all granted
    Options FollowSymLinks
    AllowOverride All
    DirectoryIndex index.php
  </Directory>

  Alias /docs /var/www/localhost/htdocs/api-docs
    <Location /docs>
      Header set Access-Control-Allow-Origin "*"
      DirectoryIndex index.html
      Require all granted
  </Location>

  ErrorLog /var/www/logs/error_api.log
  CustomLog /var/www/logs/access_api.log common
</VirtualHost>
